In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a[:2,1]

array([2, 4])

In [5]:
list("hello")

['h', 'e', 'l', 'l', 'o']

In [6]:
d = {"a": 4, 5:True, False:["a", 2, True]}

In [7]:
d

{'a': 4, 5: True, False: ['a', 2, True]}

In [8]:
tuple(("cat", "dog"))

('cat', 'dog')

dictionaries 

In [9]:
d = {"a": 1, "b": 2, "c": 0}

In [10]:
type(d.items())

dict_items

In [11]:
for k in d.items():
    print(k)
    print(type(k))

('a', 1)
<class 'tuple'>
('b', 2)
<class 'tuple'>
('c', 0)
<class 'tuple'>


In [12]:
its = d.items()
#its[0] throws TypeError
[v for k,v in its]

[1, 2, 0]

In [13]:
type(list(d.items())[1])

tuple

In [14]:
sorted(d.items(), key = lambda item: item[1])

[('c', 0), ('a', 1), ('b', 2)]

test from hw

In [15]:
def is_valid(s):
    stk = []
    for c in s:
        if c == "(" or c == "[" or c == "{":
            stk.append(c)
        elif c == ")":
            if stk[-1] != "(":
                return False
            else:
                stk.pop()
        elif c == "]":
            if stk[-1] != "[":
                return False
            else:
                stk.pop()
        elif c == "}":
            if stk[-1] != "{":
                return False
            else:
                stk.pop()
    return len(stk) == 0

comprehensions

In [16]:
[x**2 for x in range(5)]

[0, 1, 4, 9, 16]

In [17]:
{x:x**2 for x in range(5)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

multiple names for same object

In [18]:
l1 = [1,2,3]
l2 = l1

In [19]:
l1.sort(reverse = True)

In [20]:
l1

[3, 2, 1]

In [21]:
l2

[3, 2, 1]

In [22]:
l1.pop()

1

In [23]:
l2

[3, 2]

broadcasting

In [47]:
x = np.array([1,2])
y = np.array(([3],[4],[5]))
print(x)
print(y)

[1 2]
[[3]
 [4]
 [5]]


In [48]:
z = x + y
z

array([[4, 5],
       [5, 6],
       [6, 7]])

In [41]:
z + y

array([[ 7,  8],
       [ 9, 10]])

In [1]:
d = {(1,2): 3}

In [2]:
d

{(1, 2): 3}

In [3]:
a = np.array([1, 2, 3, 4, 5])
np.sum(a > 2)

np.int64(3)