### Week 6-1 NumPy Practice Problems

In [1]:
import numpy as np

### Warm up
NumPy creation and indexing.

In [2]:
# 1. Creates 3x3 array of zeros
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# 2. Creates array [0, 2, 4, 6, 8]
a = np.array([0,2,4,6,8])
a

array([0, 2, 4, 6, 8])

In [4]:
# 3. 5 evenly spaced numbers from 0 to 1
s = np.linspace(0,1,5)
s

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
# Array indexing, Gets elements > 5
arr = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

arr_l5 = arr[arr<5]
arr_l5

array([1, 2, 3, 4])

### Problem 1
Convert an array of Celsius measurements to Fahrenheit.
Note: `fahrenheit = (Celsius * 9/5) + 32`.

In [6]:
def convert_to_fahrenheit_list(temperatures):
    cels = []
    for i in range(0,len(temperatures)):
        cels.append((temperatures[i] * 9/5) + 32)

    return cels

In [7]:
print("Testing with a regular list:")
temps_list = [0, 10, 20, 30]
print(convert_to_fahrenheit_list(temps_list))

Testing with a regular list:
[32.0, 50.0, 68.0, 86.0]


In [8]:
def convert_to_fahrenheit_numpy_array(temperatures):
    temp_array = np.array(temperatures)

    return (temp_array * 9/5) + 32

In [9]:
print("\nTesting with a NumPy array:")
temps_array = np.array([0, 10, 20, 30])
print(convert_to_fahrenheit_numpy_array(temps_array))


Testing with a NumPy array:
[32. 50. 68. 86.]


### Problem 2
Use numpy to create a function that adds a border filled with zeros around an existing array.

*Hint*: Use numpy's `pad` function. See https://numpy.org/doc/stable/reference/generated/numpy.pad.html

Note: we did not cover this function in class, see if you are comfortable of reading numpy documents and learn on your own!

In [10]:
def add_border(x):
    x_arr = np.array(x)
    return np.pad(x_arr, (1,1), "constant", constant_values = 0)

In [11]:
x = np.ones((1, 1))
claimed = add_border(x)
correct = np.zeros((3, 3))
correct[1, 1] = 1.0
assert claimed.shape == correct.shape
assert np.all(np.abs(claimed - correct) < 1e-8)

In [12]:
add_border(np.array(((1,2),(1,2))))

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 1, 2, 0],
       [0, 0, 0, 0]])

### Problem 3
Create an $n \times n$ numpy array filled with a checkerboard pattern of zeros and ones. The first entry should be the integer `0`. Assume $n \ge 2$.

In [13]:
np.reshape(np.tile([0,1], 2), shape = (2,2))

array([[0, 1],
       [0, 1]])

In [14]:
n = 5
first = np.tile([0,1], int(n/2))
second = np.tile([1,0], int(n/2))

In [15]:
first_o = np.append(first,0)
second_o = np.append(second, 1)
almost = np.tile(np.array([first_o, second_o]), (int(n/2), 1))
np.append(almost, [first_o], axis = 0)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [16]:
almost

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [17]:
first_o

array([0, 1, 0, 1, 0])

In [18]:
def make_checkerboard(n):
    first = np.tile([0,1], int(n/2))
    second = np.tile([1,0], int(n/2))
    if n % 2 == 0:
        return np.tile(np.array([first, second]), (int(n/2), 1))
    if n % 2 != 0:
        first_o = np.append(first,0)
        second_o = np.append(second, 1)
        almost = np.tile(np.array([first_o, second_o]), (int(n/2), 1))
        return np.append(almost, [first_o], axis = 0)


In [19]:
make_checkerboard(n = 5)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [20]:
correct = \
    [[0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1],
     [1, 0, 1, 0, 1, 0, 1, 0]]
assert np.all(correct == make_checkerboard(8))

In [21]:
n = 6
z = np.zeros((n, n))
z[1::2,::2] = 1
z[::2, 1::2] = 1

In [22]:
z

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])